### ISSUE TITLE
有点像 The Missing Semester 的青春版

### ISSUE THREAD

**Issue by hewei2001** [criwits/missing-web#1]
有考虑过扩展更多的内容吗？作为 HITSZ 的 CS 学生，我其实见到过很多人直到大二、大三甚至都不会使用 Markdowm、写不出一份「优雅」的文档、甚至连 Git 和 GitHub 都分不清，因此我也有想过仿造 MIT 的课程做一份 HITSZ 版的 The Missing Semester，苦于事情太多还抽不出时间。

但是很高兴能看到学弟迈出这一步，非常佩服！我自己的博客（hwcoder.top）中也会记录一些诸如 Git、Linux、博客搭建的小教程，如果学弟后面有扩充这方面的打算，说不定能帮上点忙哈哈。

另外，如果想扩大项目的影响力，可以联系「院学生会权益部」供稿，他们在公众号上有个「即刻讲坛」专栏（一年前我创办的），相信你们高质量的稿件会帮助到更多人！🚀

**Comment by criwits** [comment]
实在是没想到这个已经停更许久的项目能得到关注，十分感谢学长的鼓励和肯定！

- **「有点像 The Missing Semester 的青春版」**：《你缺失的那门计算机课》的名字确实是受 _The Missing Semester_ 启发的。不过，MIT 的 _The Missing Semester_ 面向计算机专业学生，为他（我）们提供一些课上老师不会讲的工具使用教程；而这份《你缺失的那门计算机课》面向的读者是「电脑小白」，换句话说就是可能连下载安装软件、管理自己的文件都存在困难的同学。按我的观察，这类人不仅存在于我们身边，而且数量不小。这也是我开这个坑的初衷 ~~之一~~。
- **「想过仿造 MIT 的课程做一份 HITSZ 版的 The Missing Semester」**：深有体会，尤其是在各种实验课时，感觉很多同学都会「栽」在一些因缺乏我们这个专业的所谓「常识」造成的问题上。又如「写不出一份『优雅』的文档」，其实这个我也有尝试和朋友写过一份 [简明排版教程](https://hans-wan.notion.site/TypeBrief-0b3bd820f5ae45baa4a3efdd4fbc5eb9)，但因各种原因中途停下了，也许以后确实可以将这些零散的教程做在一起，编成一本适合我们专业同学的 _The Missing Semester_。
- **「如果想扩大项目的影响力，可以联系『院学生会权益部』供稿」**：其实还真有想过。《你缺失的那门计算机课》有一套使用 $\LaTeX$ 排版的 [PDF 版本](https://github.com/criwits/missing-pdf)，其实就是考虑它以后可以作为给各个专业新生的「电脑操作教程」来使用的。不过，这份 PDF 的初版就有将近 130 页（粗略《你缺失的那门计算机课》有接近 6 万字了），印成小册子估计不可能。说实话这个教程现在似乎陷入了「需要的人不会耐心看，看的人一般不需要它」的局面。也许之后进行一些增编和缩减后可以让它服务于更多人吧。
