### ISSUE TITLE
压缩文件章节内容建议

### ISSUE THREAD

**Issue by HongJunShan** [criwits/missing-web#2]
感谢作者写了这么一份精彩的教程，在**合多为一，精简空间——压缩文件**那一节提到

> 如果我们只是想查看一个压缩文件的内容，而不把它解压，或者只提取出压缩文件中的一个文件，在系统装有压缩软件的情况下可以直接双击打开压缩文件。直接双击打开压缩文件，压缩软件会展示出其中的内容。双击这里面的单个文件可以临时取出这一个文件并打开它，拖拽其中的单个文件到其他地方可以只取出这一个文件而不解压整个压缩文件。

这里如果压缩包里面是一个exe文件和其依赖，在不解压只运行exe或者运行exe后把打开的zip文件关闭的话我记得可能会导致运行有一些问题，如果确实有这样的问题，能否在这里注明下？

**Comment by criwits** [comment]
感谢您的建议。确实是这么个情况，如果直接「运行」压缩包中的 exe 很可能会因为依赖文件未被一并解压造成问题。我们之后加上相应的提示。
