### ISSUE TITLE
管理好你的文件章节建议

### ISSUE THREAD

**Issue by HongJunShan** [criwits/missing-web#3]
**管理好你的文件章节**

> 不把（重要）文件放在 C 盘。在前文我们说了，C 盘是 Windows 系统整个所在的地方。尽管发生这种情况的概率很低，但当我们的电脑因为这样或那样的原因损坏，而需要重装系统的时候，你会不得不失去 C 盘的所有文件——安装系统的第一步就是格式化 C 盘。让自己的文件远离 C 盘，是合理管理我们的文件的重要部分。

这里在某些情况下可以进PE备份出桌面或者其他文件吧？很多人重要文件我看都放桌面，能否在这里链接下进PE恢复教程（如果作者写了😃，我还没看到后面）

**Comment by criwits** [comment]
Windows PE 这个事感觉比较麻烦，首先现在很多机器默认启用 BitLocker，进 PE 也看不见文件；对于不同品牌的机器，进入 UEFI 设置找启动项的位置也不一样，还得考虑安全启动的问题，所以就没有写。不过我们可以之后考虑将它作为扩展性的内容。
